# Generated by Django 5.2.7 on 2025-10-22 15:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Utilisateur',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('userId', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('type', models.CharField(choices=[('invite', 'Invité'), ('candidat', 'Candidat'), ('entreprise', 'Entreprise')], default='invite', max_length=20)),
                ('nom', models.CharField(blank=True, max_length=100, null=True)),
                ('prenom', models.CharField(blank=True, max_length=100, null=True)),
                ('telephone', models.CharField(blank=True, max_length=20, null=True)),
                ('photoProfil', models.ImageField(blank=True, null=True, upload_to='photos_profil/')),
                ('dateNaissance', models.DateField(blank=True, null=True)),
                ('adresse', models.CharField(blank=True, max_length=255, null=True)),
                ('dateInscription', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CV',
            fields=[
                ('cvId', models.AutoField(primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=100)),
                ('fichier', models.FileField(upload_to='cvs/')),
                ('type', models.CharField(choices=[('CV', 'CV'), ('Vidéo', 'Vidéo'), ('Portfolio', 'Portfolio')], max_length=50)),
                ('dateCreation', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cvs', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Entreprise',
            fields=[
                ('entrepriseId', models.AutoField(primary_key=True, serialize=False)),
                ('nomEntreprise', models.CharField(max_length=100)),
                ('secteur', models.CharField(blank=True, max_length=100, null=True)),
                ('localisation', models.CharField(blank=True, max_length=100, null=True)),
                ('recevoirCandidatures', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='entreprise', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Envoi',
            fields=[
                ('envoiId', models.AutoField(primary_key=True, serialize=False)),
                ('domaine', models.CharField(blank=True, max_length=100, null=True)),
                ('localisation', models.CharField(blank=True, max_length=100, null=True)),
                ('dateEnvoi', models.DateTimeField(auto_now_add=True)),
                ('statut', models.CharField(choices=[('envoyé', 'Envoyé'), ('consulté', 'Consulté'), ('archivé', 'Archivé')], default='envoyé', max_length=20)),
                ('cv', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='envois', to='main.cv')),
                ('entreprise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='envois', to='main.entreprise')),
            ],
        ),
    ]
