# Generated by Django 5.2.7 on 2026-01-30 18:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Competence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=80, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Langue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Utilisateur',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=100, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('type', models.CharField(choices=[('invite', 'Invité'), ('candidat', 'Candidat'), ('entreprise', 'Entreprise')], default='invite', max_length=20)),
                ('nom', models.CharField(blank=True, max_length=100, null=True)),
                ('prenom', models.CharField(blank=True, max_length=100, null=True)),
                ('telephone', models.CharField(blank=True, max_length=20, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('dateInscription', models.DateTimeField(auto_now_add=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CV',
            fields=[
                ('cvId', models.AutoField(primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=100)),
                ('fichier', models.FileField(upload_to='cvs/')),
                ('type', models.CharField(choices=[('cv', 'CV'), ('video', 'Vidéo'), ('portfolio', 'Portfolio')], default='cv', max_length=20)),
                ('dateCreation', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cvs', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Entreprise',
            fields=[
                ('entrepriseId', models.AutoField(primary_key=True, serialize=False)),
                ('nomEntreprise', models.CharField(max_length=150)),
                ('secteur', models.CharField(blank=True, max_length=120, null=True)),
                ('ville', models.CharField(blank=True, max_length=100, null=True)),
                ('pays', models.CharField(default='Algérie', max_length=100)),
                ('recevoirCandidatures', models.BooleanField(default=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='entreprise', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Offre',
            fields=[
                ('offreId', models.AutoField(primary_key=True, serialize=False)),
                ('titre', models.CharField(max_length=150)),
                ('poste', models.CharField(blank=True, max_length=150, null=True)),
                ('domaine', models.CharField(max_length=120)),
                ('specialite', models.CharField(blank=True, max_length=120, null=True)),
                ('niveau', models.CharField(blank=True, choices=[('junior', 'Junior'), ('intermediaire', 'Intermédiaire'), ('senior', 'Senior'), ('lead', 'Lead'), ('manager', 'Manager')], max_length=30, null=True)),
                ('type_contrat', models.CharField(choices=[('cdi', 'CDI'), ('cdd', 'CDD'), ('stage', 'Stage'), ('freelance', 'Freelance'), ('alternance', 'Alternance')], max_length=20)),
                ('mode_travail', models.CharField(choices=[('site', 'Sur site'), ('hybride', 'Hybride'), ('remote', 'Remote')], max_length=20)),
                ('experience_min', models.PositiveIntegerField(blank=True, null=True)),
                ('experience_max', models.PositiveIntegerField(blank=True, null=True)),
                ('etude_min', models.CharField(choices=[('aucun', 'Aucun'), ('bac', 'Bac'), ('licence', 'Licence'), ('master', 'Master'), ('doctorat', 'Doctorat')], default='aucun', max_length=20)),
                ('salaire_min', models.PositiveIntegerField(blank=True, null=True)),
                ('salaire_max', models.PositiveIntegerField(blank=True, null=True)),
                ('devise', models.CharField(default='DZD', max_length=10)),
                ('description', models.TextField(blank=True, null=True)),
                ('missions', models.TextField(blank=True, null=True)),
                ('profil_recherche', models.TextField(blank=True, null=True)),
                ('avantages', models.TextField(blank=True, null=True)),
                ('tags', models.CharField(blank=True, max_length=255, null=True)),
                ('ville', models.CharField(blank=True, max_length=100, null=True)),
                ('pays', models.CharField(default='Algérie', max_length=100)),
                ('relance_days', models.PositiveIntegerField(default=7)),
                ('recevoirCandidatures', models.BooleanField(default=False)),
                ('estPubliee', models.BooleanField(default=False)),
                ('estArchivee', models.BooleanField(default=False)),
                ('dateLimite', models.DateField(blank=True, null=True)),
                ('dateCreation', models.DateTimeField(auto_now_add=True)),
                ('competences', models.ManyToManyField(blank=True, to='main.competence')),
                ('entreprise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offres', to='main.entreprise')),
                ('langues', models.ManyToManyField(blank=True, to='main.langue')),
            ],
        ),
        migrations.CreateModel(
            name='Envoi',
            fields=[
                ('envoiId', models.AutoField(primary_key=True, serialize=False)),
                ('entreprise_nom_snapshot', models.CharField(blank=True, max_length=150, null=True)),
                ('offre_titre_snapshot', models.CharField(blank=True, max_length=150, null=True)),
                ('offre_domaine_snapshot', models.CharField(blank=True, max_length=120, null=True)),
                ('offre_ville_snapshot', models.CharField(blank=True, max_length=100, null=True)),
                ('offre_pays_snapshot', models.CharField(blank=True, max_length=100, null=True)),
                ('dateEnvoi', models.DateTimeField(auto_now_add=True)),
                ('statut', models.CharField(choices=[('envoye', 'Envoyé'), ('en_attente', 'En attente'), ('accepte', 'Accepté'), ('refuse', 'Refusé')], default='envoye', max_length=20)),
                ('cv', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='envois', to='main.cv')),
                ('offre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='envois', to='main.offre')),
            ],
        ),
        migrations.AddIndex(
            model_name='offre',
            index=models.Index(fields=['domaine'], name='main_offre_domaine_03f9e6_idx'),
        ),
        migrations.AddIndex(
            model_name='offre',
            index=models.Index(fields=['specialite'], name='main_offre_special_2510dc_idx'),
        ),
        migrations.AddIndex(
            model_name='offre',
            index=models.Index(fields=['ville'], name='main_offre_ville_3e298f_idx'),
        ),
        migrations.AddIndex(
            model_name='offre',
            index=models.Index(fields=['pays'], name='main_offre_pays_7d1e68_idx'),
        ),
        migrations.AddIndex(
            model_name='offre',
            index=models.Index(fields=['type_contrat'], name='main_offre_type_co_875da5_idx'),
        ),
        migrations.AddIndex(
            model_name='offre',
            index=models.Index(fields=['mode_travail'], name='main_offre_mode_tr_3f5658_idx'),
        ),
        migrations.AddIndex(
            model_name='offre',
            index=models.Index(fields=['niveau'], name='main_offre_niveau_68a154_idx'),
        ),
        migrations.AddIndex(
            model_name='offre',
            index=models.Index(fields=['estPubliee', 'recevoirCandidatures', 'estArchivee'], name='main_offre_estPubl_295eab_idx'),
        ),
        migrations.AddIndex(
            model_name='envoi',
            index=models.Index(fields=['dateEnvoi'], name='main_envoi_dateEnv_2a91ad_idx'),
        ),
        migrations.AddIndex(
            model_name='envoi',
            index=models.Index(fields=['statut'], name='main_envoi_statut_bb64ae_idx'),
        ),
        migrations.AddIndex(
            model_name='envoi',
            index=models.Index(fields=['cv', 'offre', 'dateEnvoi'], name='main_envoi_cv_id_b67551_idx'),
        ),
    ]
