# Generated by Codex on 2026-01-31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="utilisateur",
            name="dateNaissance",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="utilisateur",
            name="photoProfil",
            field=models.ImageField(blank=True, null=True, upload_to="photos_profil/"),
        ),
    ]
