# Generated by Django 5.2.7 on 2025-11-06 18:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_utilisateur_email_alter_utilisateur_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='utilisateur',
            old_name='userId',
            new_name='id',
        ),
    ]
