# Generated by Django 5.2.4 on 2026-01-29 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_rename_userid_utilisateur_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entreprise',
            name='localisation',
        ),
        migrations.RemoveField(
            model_name='envoi',
            name='localisation',
        ),
        migrations.AddField(
            model_name='entreprise',
            name='adresse',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Adresse complète'),
        ),
        migrations.AddField(
            model_name='entreprise',
            name='code_postal',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Code postal'),
        ),
        migrations.AddField(
            model_name='entreprise',
            name='pays',
            field=models.CharField(default='Algérie', max_length=100, verbose_name='Pays'),
        ),
        migrations.AddField(
            model_name='entreprise',
            name='ville',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Ville'),
        ),
        migrations.AddField(
            model_name='envoi',
            name='adresse',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Adresse complète'),
        ),
        migrations.AddField(
            model_name='envoi',
            name='code_postal',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Code postal'),
        ),
        migrations.AddField(
            model_name='envoi',
            name='pays',
            field=models.CharField(default='Algérie', max_length=100, verbose_name='Pays'),
        ),
        migrations.AddField(
            model_name='envoi',
            name='ville',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Ville'),
        ),
    ]
