# Generated by Django 5.2.4 on 2026-01-29 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_remove_entreprise_localisation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cv',
            name='type',
            field=models.CharField(choices=[('cv', 'CV'), ('video', 'Vidéo'), ('portfolio', 'Portfolio')], max_length=20),
        ),
        migrations.AlterField(
            model_name='entreprise',
            name='adresse',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='entreprise',
            name='code_postal',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='entreprise',
            name='nomEntreprise',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='entreprise',
            name='pays',
            field=models.CharField(default='Algérie', max_length=100),
        ),
        migrations.AlterField(
            model_name='entreprise',
            name='recevoirCandidatures',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='entreprise',
            name='ville',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='envoi',
            name='adresse',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='envoi',
            name='code_postal',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='envoi',
            name='pays',
            field=models.CharField(default='Algérie', max_length=100),
        ),
        migrations.AlterField(
            model_name='envoi',
            name='statut',
            field=models.CharField(choices=[('envoye', 'Envoyé'), ('en_attente', 'En attente'), ('accepte', 'Accepté'), ('refuse', 'Refusé')], default='envoye', max_length=20),
        ),
        migrations.AlterField(
            model_name='envoi',
            name='ville',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
