# Generated by Django 5.2.4 on 2026-01-29 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_cv_type_alter_entreprise_adresse_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='envoi',
            name='adresse',
        ),
        migrations.RemoveField(
            model_name='envoi',
            name='code_postal',
        ),
        migrations.RemoveField(
            model_name='envoi',
            name='pays',
        ),
        migrations.RemoveField(
            model_name='envoi',
            name='ville',
        ),
        migrations.AddField(
            model_name='envoi',
            name='localisation',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='cv',
            name='type',
            field=models.CharField(choices=[('CV', 'CV'), ('Vidéo', 'Vidéo'), ('Portfolio', 'Portfolio')], max_length=50),
        ),
        migrations.AlterField(
            model_name='entreprise',
            name='adresse',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Adresse complète'),
        ),
        migrations.AlterField(
            model_name='entreprise',
            name='code_postal',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Code postal'),
        ),
        migrations.AlterField(
            model_name='entreprise',
            name='nomEntreprise',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='entreprise',
            name='pays',
            field=models.CharField(default='Algérie', max_length=100, verbose_name='Pays'),
        ),
        migrations.AlterField(
            model_name='entreprise',
            name='recevoirCandidatures',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='entreprise',
            name='ville',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Ville'),
        ),
        migrations.AlterField(
            model_name='envoi',
            name='statut',
            field=models.CharField(choices=[('envoyé', 'Envoyé'), ('consulté', 'Consulté'), ('archivé', 'Archivé')], default='envoyé', max_length=20),
        ),
    ]
